session_name: nixvim
start_directory: /home/hamburgir/repo/nixvim
windows:
  - window_name: editor
    layout: main-horizontal
    panes:
      - nvim
      - agy
  - window_name: runner
    panes:
      - shell_command:
        - cmd: nix run .
          enter: false
