session_name: nixvim
start_directory: /home/hamburgir/repo/nixvim
windows:
  - window_name: editor
    layout: even-horizontal
    panes:
      - nvim
      - agy
  - window_name: runner
    panes:
      - tmux send-keys 'nix run .'
